# Generated by Django 5.1.7 on 2025-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_policestation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Kottayam', 'Kottayam')], max_length=100)),
                ('location', models.CharField(choices=[('Pala', 'Pala')], max_length=255)),
                ('complaint_type', models.CharField(choices=[('robbery', 'Robbery'), ('hit_and_run', 'Hit and Run')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('approximate_time', models.CharField(max_length=50)),
            ],
        ),
    ]
