# Generated by Django 5.1.7 on 2025-03-08 15:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='approximate_time',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='date_filed',
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under investigation', 'Under Investigation'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='time',
            field=models.CharField(choices=[('midnight', '12:00AM - 12:59AM'), ('morning', '6:00AM - 11:59AM')], default='abcd', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('robbery', 'Robbery'), ('hit and run', 'Hit and Run')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_complaints', to='core.policestation'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_complaints', to='core.policestation'),
        ),
    ]
