# Generated by Django 5.1.7 on 2025-03-08 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_complaint_approximate_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='time',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='pincode',
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_date',
            field=models.DateField(default='2025-03-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='submission_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='time_of_incident',
            field=models.CharField(choices=[('midnight', '12:00 AM - 12:59 AM'), ('morning', '6:00 AM - 11:59 AM'), ('noon', '12:00 PM - 12:59 PM'), ('afternoon', '1:00 PM - 5:59 PM'), ('evening', '6:00 PM - 8:59 PM'), ('night', '9:00 PM - 11:59 PM')], default='abc', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policestation',
            name='name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('robbery', 'Robbery'), ('assault', 'Assault'), ('threats', 'Threats'), ('burglary', 'Burglary'), ('vandalism', 'Vandalism'), ('fraud', 'Fraud'), ('harassment', 'Harassment'), ('theft', 'Theft'), ('domestic violence', 'Domestic Violence'), ('sexual assault', 'Sexual Assault'), ('kidnapping', 'Kidnapping'), ('stalking', 'Stalking'), ('drunk driving', 'Drunk Driving'), ('hit and run', 'Hit and Run'), ('drug offenses', 'Drug Offenses'), ('public intoxication', 'Public Intoxication'), ('trespassing', 'Trespassing'), ('hate crimes', 'Hate Crimes'), ('murder', 'Murder'), ('arson', 'Arson'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
