# Generated by Django 5.1.7 on 2025-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_complaint_date_remove_complaint_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policestation',
            name='contact',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policestation',
            name='password',
            field=models.CharField(default='00', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policestation',
            name='pincode',
            field=models.CharField(default='00000', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('robbery', 'Robbery'), ('assault', 'Assault'), ('threats', 'Threats'), ('burglary', 'Burglary'), ('vandalism', 'Vandalism'), ('fraud', 'Fraud'), ('harassment', 'Harassment'), ('theft', 'Theft'), ('domestic_violence', 'Domestic Violence'), ('sexual_assault', 'Sexual Assault'), ('kidnapping', 'Kidnapping'), ('stalking', 'Stalking'), ('drunk_driving', 'Drunk Driving'), ('hit_and_run', 'Hit and Run'), ('drug_offenses', 'Drug Offenses'), ('public_intoxication', 'Public Intoxication'), ('trespassing', 'Trespassing'), ('hate_crimes', 'Hate Crimes'), ('murder', 'Murder'), ('arson', 'Arson'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='incident_date',
            field=models.DateField(help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
