# Generated by Django 5.1.7 on 2025-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_policestation_approved_policestation_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='name',
        ),
        migrations.AlterField(
            model_name='policestation',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
