# Generated by Django 5.1.7 on 2025-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_policestation_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
